### PR TITLE
Configurable feature to reset MCU if it doesn't show any activity

### PR DESCRIPTION
**Pull request by dyarkovoy**

### CODE REVIEW

**Comment by leodesigner** [comment]
I had to manually merge this pull request.
Good idea BTW.
I am not sure how to deal with conflicting firmware/user1.bin firmware/user2.bin files yet.
Thanks anyway.

**Comment by leodesigner** [comment]
It would be good to check if the SLIP is enabled too before activating the watchdog action.

**Comment by leodesigner** [comment]
Just added additional commit to check is the SLIP enabled.

**Comment by dyarkovoy** [comment]
Thanks and sorry for the binaries, I added them to .gitignore on my side and removed from the repo to avoid conflicts in the future. Nice catch with the SLIP.

**Pull request closed without merging**
